export const menuItem = [
  {
    name: "DISCOVER SP MEDIFORT",
    url: "/discover",
    dropdown: [
      { name: "About Us", url: "/discover/about" },
      { name: "Careers", url: "/discover/careers" },
    ],
  },
  {
    name: "SPECIALITIES & TREATMENT",
    url: "/specialities",
    dropdown: [
      {
        name: "Treatment Services",
        url: "/specialities/treatments",
        subMenuItem: [
          { name: "Physiotherapy & Rehabilitation", url: "/services/physiotherapy-rehabilitation" },
          { name: "Clinical Laboratory", url: "/services/clinical-laboratory" },
          { name: "Pharmacy", url: "/services/pharmacy" },
          { name: "Cath Lab", url: "/services/cath-lab" },
          { name: "Nursing Services", url: "/services/nursing-services" },
          { name: "Blood Centre", url: "/services/blood-centre" },
          { name: "Medical Records", url: "/services/medical-records" },
          { name: "Audiology & Speech Therapy", url: "/services/audiology-speech-therapy" },
          { name: "Imaging Services", url: "/services/imaging-services" },
          { name: "EMG / EEG / ECG", url: "/services/emg-eeg-ecg" },
          { name: "Dietetics & Nutrition", url: "/services/dietetics-nutrition" },
          { name: "CSSD (Central Sterile Services Department)", url: "/services/cssd" },
        ],
      },
    //   {
    //     name: "Departments",
    //     url: "/specialities/departments",
    //     subMenuItem: [
    //       { name: "Cardiac Science", url: "/departments/cardiac-science" },
    //       { name: "Anesthesiology", url: "/departments/anesthesiology" },
    //       { name: "Critical Care", url: "/departments/critical-care" },
    //       { name: "Dental Oral & Maxillo Facial Surgery", url: "/departments/dental-oral-maxillofacial" },
    //       { name: "Department of Surgery", url: "/departments/surgery" },
    //       { name: "Dermatology", url: "/departments/dermatology" },
    //       { name: "Emergency Medicine", url: "/departments/emergency-medicine" },
    //       { name: "Endocrinology", url: "/departments/endocrinology" },
    //       { name: "ENT", url: "/departments/ent" },
    //       { name: "Family Medicine", url: "/departments/family-medicine" },
    //       { name: "Gastroenterology", url: "/departments/gastroenterology" },
    //       { name: "General Medicine", url: "/departments/general-medicine" },
    //       { name: "Laryngology", url: "/departments/laryngology" },
    //       { name: "Nephrology", url: "/departments/nephrology" },
    //       { name: "Neuroscience", url: "/departments/neuroscience" },
    //       { name: "Obstetrics & Gynaecology", url: "/departments/obstetrics-gynaecology" },
    //       { name: "Oncology", url: "/departments/oncology" },
    //       { name: "Ophthalmology", url: "/departments/ophthalmology" },
    //       { name: "Orthopedics & Spine", url: "/departments/orthopedics-spine" },
    //       { name: "Pediatrics", url: "/departments/pediatrics" },
    //       { name: "Plastic & Micro Vascular Surgery", url: "/departments/plastic-micro-vascular" },
    //       { name: "Psychiatry", url: "/departments/psychiatry" },
    //       { name: "Radiodiagnosis", url: "/departments/radiodiagnosis" },
    //       { name: "Respiratory Medicine", url: "/departments/respiratory-medicine" },
    //       { name: "Rheumatology", url: "/departments/rheumatology" },
    //       { name: "Speech Therapy", url: "/departments/speech-therapy" },
    //       { name: "Urology", url: "/departments/urology" },
    //     ],
    //   },
    ],
  },
  {
    name: "SERVICES",
    url: "/services",
    dropdown: [
      { name: "Medical Services", url: "/services/medical-services" },
      { name: "Health Check Packages", url: "/services/#" },
      { name: "Find a Doctor", url: "/services/#" },
      { name: "Book Appointment", url: "/services/#" },
      { name: "Patient Testimonial", url: "/services/#" },
    ],
  },
  {
    name: "INTERNATIONAL PATIENTS",
    url: "/international",
    // dropdown: [
    //   { name: "Patient Care", url: "/international/patient-Care" },
    //   { name: "International Patient Care", url: "/international/international-patient-care" },
    // ],
  },
  {
    name: "HOSPITAL FACILITIES",
    url: "/facilities",
    // dropdown: [
    //   { name: "Hospital Facilities", url: "/facilities/hospital-facilities" },
    //   { name: "Advanced Technology & Infrastructure", url: "/facilities/parking" },
    // ],
  },
  {
    name: "CONTACT US",
    url: "/contact",
    // dropdown: [
    //   { name: "Contact Us", url: "/contact/info" },
    //   { name: "Book Appointment", url: "/contact/feedback" },
    // ],
  },
];
